name: dynamic_app_icon
description: A Flutter plugin that lets you change the icon for the app dynamically.
version: 1.0.2
author: aleksander.slater@olavstoppen.no
homepage: https://olavstoppen.no

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: no.olavstoppen.plugins.dynamic_app_icon
    pluginClass: DynamicAppIconPlugin
